# Generated by Django 4.2 on 2023-04-17 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_orders', '0001_initial'),
        ('movies', '0003_movieorder_movie_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(related_name='order_movies', through='movie_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MovieOrder',
        ),
    ]
